### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by binhtendo** [binhtendo/capstone-project#12]
## Value Proposition

**As a** user
**I want to** favorite the displayed places in the list by clicking on a button and collect them separately on another page
**so that** I get a favorite overview of which places I would like to visit. 
​

## Description

​
<img width="437" alt="toggle US" src="https://user-images.githubusercontent.com/122276595/227234180-75a00479-b303-4fa8-9e8e-875dd74b7bf7.png">

## Acceptance Criteria

- [ ] for each entry a toggle button (add/remove)
- [ ] save and display the favorite entries on the page /favorites
- [ ] the entries on the /favorites page should also be removable again
      ​

## Tasks

- [ ] create a new component to toggle the entries / places
- [ ] define a new function handlefavorite in the searchbox component
- [ ] create /favorites under pages
      ​
