### ISSUE TITLE
filter function

### ISSUE THREAD

**Issue by binhtendo** [binhtendo/capstone-project#16]
## Value Proposition

**As a** user
**I want to** filter the results displayed by entering a location (for example Eifel Tower)
**so that** i can favor that location more quickly.
​

## Description
​
<img width="256" alt="filter" src="https://user-images.githubusercontent.com/122276595/227961690-8ed17ef6-cd8e-4c61-a00c-3a425490ff93.png">

## Acceptance Criteria

- [ ] an inputfield below the searchfield 

## Tasks

- [ ] create a new branch "filter"
- [ ] create a new component (e.g. Filter)
- [ ] use React useState to integrate the component Filter into component Searchbox 
      ​
