### ISSUE TITLE
pagination buttons

### ISSUE THREAD

**Issue by binhtendo** [binhtendo/capstone-project#18]
## Value Proposition

**As a** user
**I want to** to have a back and next button
**so that**  i can click through the many entries in smaller blocks 
​

## Description

​
<img width="222" alt="backnextbutton" src="https://user-images.githubusercontent.com/122276595/228310322-5cc967ff-22ee-4d1a-b5a5-a4df048f3836.png">

## Acceptance Criteria

- [ ] show for example the first 10 results with the two buttons at the bottom 
- [ ] previous button left und next button on the right
- [ ] click through the results till the end
      ​

## Tasks

- [ ] create new branch (pagination)
- [ ] use useSate 
- [ ] create previous button and next button
- [ ] set the number displayed per page
